class Constants {
  static const double kPadding = 20;
  static const int iphoneLimit = 640;
  static const int ipadLimit = 900;
  static const double standarSize = 150;
  static const apiKey = "1ecc951a582d4ec4a12f94918c64bd4b";
  static const String dummyText =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a nisi nisi. Donec sed tincidunt est. Nullam fermentum ex at erat congue interdum sed ut ante. Maecenas ac vulputate justo. Ut scelerisque risus ut laoreet feugiat. Sed pharetra arcu sed tempus laoreet. Praesent sit amet tincidunt justo. Sed tincidunt fermentum quam ac luctus. Nam rhoncus tristique libero, non pretium tellus rutrum malesuada. Integer fermentum sed ipsum nec pretium. Pellentesque convallis ac purus sed accumsan. Vivamus sit amet gravida nibh. Duis scelerisque vitae lectus nec bibendum. Phasellus nulla quam, cursus ut ex quis, bibendum dictum velit." +
          "Aenean fringilla magna eu neque laoreet, ac faucibus ex blandit. Duis venenatis interdum arcu, quis sollicitudin enim aliquet at. Mauris vehicula pretium tortor porttitor tristique. Suspendisse eget tellus dui. Praesent vestibulum justo quis lectus efficitur, ut tincidunt justo posuere. Etiam ut lectus quis sem rhoncus fringilla. Phasellus sodales ultricies lobortis. Suspendisse ut neque rhoncus, facilisis purus convallis, tempus velit. Praesent eu ligula mattis libero ornare laoreet eu quis nulla. Suspendisse tristique ante sit amet velit congue tincidunt. Sed tempor elementum nulla, id euismod magna. Nulla consequat eu turpis id viverra. Aliquam mauris arcu, rhoncus ut fermentum quis, consectetur eu massa. In nec lorem laoreet, ultrices nunc ut, suscipit turpis. Proin pulvinar lacus nibh, id malesuada metus tristique a. Integer fringilla nibh velit, ac finibus ex vestibulum vitae." +
          "Fusce in varius velit. Nulla volutpat pellentesque mattis. Nam bibendum cursus arcu, at feugiat purus egestas id. Nulla sodales at turpis et ultricies. Pellentesque ac scelerisque quam. Sed ut odio in leo sodales porttitor. Maecenas sollicitudin purus eu lacus blandit, vel bibendum ipsum bibendum. Quisque cursus tincidunt quam, eget tristique magna." +
          "Donec vel arcu vel dolor ultricies aliquam. Praesent a ex metus. Nunc id placerat nulla, quis lobortis tellus. Maecenas velit neque, vulputate vel ante non, cursus mattis nulla. Etiam vel pharetra ex. Quisque scelerisque eleifend consequat. Sed eleifend vulputate lorem non egestas. Suspendisse in vestibulum nunc. Duis sapien velit, ullamcorper ac dolor nec, dictum porta urna. Praesent vel eleifend ipsum, eget molestie justo. Duis mattis, nibh quis porttitor condimentum, risus arcu vulputate velit, a varius metus nulla id eros."
              "Pellentesque ultrices interdum imperdiet. Maecenas nec aliquet arcu, non lobortis felis. Nunc ac arcu sed felis porttitor sodales. Donec pharetra nunc vel velit viverra, ac porttitor metus venenatis. Sed sit amet maximus lorem. Donec sit amet pharetra ipsum, at aliquam justo. Aenean sollicitudin quam euismod eleifend euismod.";
}
